### ISSUE TITLE
ManifestSigningService does not pass in the PULP_CONTAINER_SIGNING_KEY_FINGERPRINT when calling sign()

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp_container#1034]
The GalaxyNG signing script[0] used for the ManifestSigningService expects PULP_CONTAINER_SIGNING_KEY_FINGERPRINT environment variable. However, the ManifestSigningService does not pass that to the sign() method[1]. 

[0] https://github.com/rochacbruno/galaxy_ng/blob/master/docs/config/container_signing.md#the-signing-script
[1] https://github.com/pulp/pulp_container/blob/6ad718437be26fa77dd4b25bc913a8a3dc4b9e87/pulp_container/app/models.py#L457-L459

**Comment by mdellweg** [comment]
https://github.com/pulp/pulpcore/blob/main/pulpcore/app/models/content.py#L755
We pass the fingerprint. The script is looking for the wrong variable.

**Comment by lubosmj** [comment]
As @mdellweg said, the script should use `PULP_SIGNING_KEY_FINGERPRINT` instead. I am closing this issue.

**Comment by mikedep333** [comment]
@lubosmj @mdellweg Just to confirm, the script utilizes PULP_SIGNING_KEY_FINGERPRINT, but pulpcore-worker needs [PULP_CONTAINER_SIGNING_KEY_FINGERPRINT](https://github.com/ansible/galaxy_ng/pull/1414/files#diff-3625086a82ee6c27ec3c8f14998bf400b7877b843323ad6f5e57acf555e090d5R75), correct?

**Comment by lubosmj** [comment]
@mikedep333, No. The attached script reads `PULP_CONTAINER_SIGNING_KEY_FINGERPRINT` which is wrong. Signing services always set the `PULP_SIGNING_KEY_FINGERPRINT` environment variable regardless of the entity running the signing service. The variable is set automatically from the value saved in the database (`pubkey_fingerprint`: https://github.com/pulp/pulpcore/blob/cd3a090f5c39171d2326a7a8c3cb682451af2d00/pulpcore/app/models/content.py#L734) once a user executes the signing procedure from the API.

There should be always used `PULP_SIGNING_KEY_FINGERPRINT`. See the script shown in the documentation: https://docs.pulpproject.org/pulp_container/workflows/sign-images.html#image-signature-configuration. One of the constraints is the use of environment variables:

> Environment variables passed to the script cannot be changed since these are the variables expected by the signing facility.

The workers always call the same execution method to sign content. So, they just forward the environment variables to the script.
