### ISSUE TITLE
Add tests for the import/export feature

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1035]
We should add tests verifying the import/export feature.

Similarly to this: https://github.com/pulp/pulp_rpm/commit/3f30ee4eebf23707d99a32905e839dac4a6b0e84, we may add a test that verifies the creation of missing repositories in addition to a test case where repositories of the push type are imported as repositories of the sync type.

**Comment by mdellweg** [comment]
https://github.com/pulp/pulp_container/blob/main/pulp_container/tests/functional/api/test_pulpimportexport.py

**Comment by lubosmj** [comment]
Then, we only need to add tests for the new "create_repositories" option. Which can be added in this PR: https://github.com/pulp/pulp_container/pull/826. I am closing this issue in favour of https://github.com/pulp/pulp_container/issues/825.
