### ISSUE TITLE
As a user during sync of remote repo I have first checked wehther manifests exist locally

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1047]
**Version**
main and older

**Describe the bug**
Every time we sync/re-sync a repo it downloads the tag list and all manifests https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L112

Instead of sending the GET request to the remote registry that can have pull rate limiting in place, we could first issue a HEAD request to the url and retrieve `docker-content-digest` from the response headers. Subsequently check whether there is already such manifest digest in the database and in case there is one we  can re-use it and avoid sending unnecessary GET requests to the remote source.

**Concrete example that shows benefits:**

Repo A has 100 tags, on every re-sync we will downloaded 100 manifests that would be equal to 100 pulls.

**Comment by mdellweg** [comment]
In the docker api, a get on a tag returns the Manifest, but we can also retrieve that manifest via it's digest (we get from a head request), right?
So we could clean up the sync pipeline by "downloading" tags via HEAD and just add their digest to the list of Manifests we want to download anyway? At that point the pipeline should do the deduplication for us. (Maybe this is too crazy...)

**Comment by ipanova** [comment]
Once we get the digest from the HEAD request we need to check whether Tag with such name and manifest pk already exists.
1) If yes then there is no need to issue a GET request. Account for the case when such Tag exists in the repo or in some other repo.
2) If digest has changed and there is a manifest
3)  there is no such manifest digest

**Comment by mdellweg** [comment]
I agree, but i think we also need to create DC's for all the (probably existing) Blobs too.

**Comment by ipanova** [comment]
Not necessarily, if we pass `content_data` ( loaded manifest json) together with manifest_dc to the blob creation. First stage will create blobs_dc and pass it to the pipeline which then will discover existing blobs through the query_existing_artifacts/content stages

**Comment by ipanova** [comment]
I think in the end it will boil down to instead of downloading new bits and saving those as artifact , find them locally https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L130 and together with loaded json from that artifact file https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L137 pass them both to the dc creation depending on the media_type [0] [1]
[0] https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L143
[1] https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L187

**Comment by ipanova** [comment]
```
diff --git a/pulp_container/app/tasks/sync_stages.py b/pulp_container/app/tasks/sync_stages.py
index cdb3c5ed..0f04373f 100644
--- a/pulp_container/app/tasks/sync_stages.py
+++ b/pulp_container/app/tasks/sync_stages.py
@@ -113,7 +113,7 @@ class ContainerFirstStage(Stage):
                 name=self.remote.namespaced_upstream_name, tag=tag_name
             )
             url = urljoin(self.remote.url, relative_url)
-            downloader = self.remote.get_downloader(url=url)
+            downloader = self.remote.head_downloader(url=url)
             to_download.append(downloader.run(extra_data={"headers": V2_ACCEPT_HEADERS}))
 
         async with ProgressReport(
@@ -124,13 +124,28 @@ class ContainerFirstStage(Stage):
 
             for download_tag in asyncio.as_completed(to_download):
                 dl_res = await download_tag
-                with open(dl_res.path, "rb") as content_file:
-                    raw_data = content_file.read()
-                dl_res.artifact_attributes["file"] = dl_res.path
-                saved_artifact = await sync_to_async(_save_artifact_blocking)(
-                    dl_res.artifact_attributes
-                )
-
+                digest = dl_res.headers.get("docker-content-digest")
+                manifest = await sync_to_async(
+                Manifest.objects.prefetch_related("contentartifact_set").filter(digest=digest).first
+                )()
+                if manifest:
+
+                    def _get_content_data_blocking():
+                    saved_artifact = manifest.contentartifact_set.first().artifact
+                    raw_data = saved_artifact.file
+                    saved_artifact.file.close()
+                   return saved_artifact, content_data
+
+                   saved_artifact, raw_data = await sync_to_async(_get_content_data_blocking)()
+               else:
+                    downloader = self.remote.get_downloader(url=dl_res.url)
+                    dl_res = await downloader.run(extra_data={"headers": V2_ACCEPT_HEADERS})
+                    with open(dl_res.path, "rb") as content_file:
+                        raw_data = content_file.read()
+                    dl_res.artifact_attributes["file"] = dl_res.path
+                    saved_artifact = await sync_to_async(_save_artifact_blocking)(
+                        dl_res.artifact_attributes
+                    )
                 tag_name = dl_res.url.split("/")[-1]
                 tag_dc = DeclarativeContent(Tag(name=tag_name))
```
