### ISSUE TITLE
 Add upper and lower bounds to all pulp_container dependencies #3232 

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1093]
Per [the new dependency docs](https://github.com/pulp/pulpcore/blob/main/docs/plugins/plugin-writer/concepts/index.rst#declaring-dependencies) we should add an upper and lower bound for all dependencies.

This does not need to be done for the functional and test dependencies, just the runtime pulp_container dependencies.

**Comment by fao89** [comment]
this policy will make issues like this more frequent:
https://github.com/pulp/pulp_container/issues/1083
