### ISSUE TITLE
Pulp_container 2.14 adds a new field 'signed_only' which is not recognized by 2.10

### ISSUE THREAD

**Issue by sjha4** [pulp/pulp_container#1122]
**Version**
Pulpcore 3.21
Master version : [python39-pulp-container-2.14.0-2.el8.noarch.rpm](http://koji.katello.org/releases/yum/pulpcore-3.21/el8/x86_64/python39-pulp-container-2.14.0-2.el8.noarch.rpm)
Proxy version: 
[python39-pulp-container-2.10.9-1.el8.noarch.rpm](http://koji.katello.org/releases/yum/pulpcore-3.18/el8/x86_64/python39-pulp-container-2.10.9-1.el8.noarch.rpm)

Please provide the versions of the pulpcore and pulp_container packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
When syncing a container repo on proxy from master, using ruby bindings on master, the field signed_only is added to RepositorySyncURL object and passed to pulp API on proxy, v 2.10 in our case which fails when it sees the unexpected "signed_only" parameter. 

**To Reproduce**

I am not sure how to translate the steps to plugin since this is binding specific as far as katello is concerned.

For the bindings, the behavior is as following:

repoSyncUrl = PulpContainerClient::ContainerRepositorySyncURL.new({remote: pulp_href_of_remote, mirrror: true})
puts repoSyncUrl

{remote: pulp_href_of_remote, mirrror: true, signed_only: false}

This new RepositorySyncURL with the extra field signed_only defaulted to false is sent to the 2.10 container API and causes the error:
Error: Error message: the server returns an error
HTTP status code: 400
Response headers: {"date"=>"Wed, 26 Oct 2022 23:38:48 GMT", "server"=>"gunicorn", "content-type"=>"application/json", "vary"=>"Accept,Cookie", "allow"=>"POST, OPTIONS", "x-frame-options"=>"DENY", "content-length"=>"36", "x-content-type-options"=>"nosniff", "referrer-policy"=>"same-origin", "correlation-id"=>"423a16fd-23cf-42a4-a02b-a6e0c2a7150c", "access-control-expose-headers"=>"Correlation-ID", "via"=>"1.1 pipe-up-katello-proxy-nightly-almalinux8.example.com", "connection"=>"close"}
Response body: {"signed_only":["Unexpected field"]} 

**Expected behavior**
Either 2.14 bindings will need to be updated to ignore the signed_only value if null when passing it to the API, or 2.10 should accept and ignore the signed_only param. Both will solve katello's issue. :)

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by sjha4** [comment]
@ggainey @gerrod3 @ipanova : Please treat this as P1 from katello's perspective. 🙂

**Comment by lubosmj** [comment]
Seems like the issue was already addressed in https://github.com/theforeman/pulpcore-packaging/pull/597?
