### ISSUE TITLE
Validate manifest  raises wrong digest in case this is a schema1 type 

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1130]
**Version**
master - 2.15.dev

**Describe the bug**
validate_manifest raises wrong digest in case this is a schema1 type https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sync_stages.py#L140. Digest of schema1 manifest should be  calculated after stripping its signature 

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by lubosmj** [comment]
This is now relevant to https://github.com/pulp/pulp_container/blob/d6201aad9a9befdcdbaf8d4e578da380e118e8d2/pulp_container/app/tasks/sync_stages.py#L149, right?

**Comment by ipanova** [comment]
yes

**Comment by git-hyagi** [comment]
fixed by https://github.com/pulp/pulp_container/pull/1530
https://github.com/pulp/pulp_container/pull/1530/files#diff-b702cbd3ebdff19bf8e4dfc14688aa3fb36e1a47ef6cf84d24e0f75b61247d36R147
