### ISSUE TITLE
Sync of busybox from dockerhub fails

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1156]
**Version**
main 

**Describe the bug**
1. sync library/busybox from dockerhub
2. Task fails with `"description": "{'errors': [{'code': ErrorDetail(string='MANIFEST_INVALID', code='parse_error'), 'message': ErrorDetail(string=\"config.mediaType: 'application/octet-stream' is not one of ['application/vnd.docker.container.image.v1+json']\", code='parse_error'), 'detail': {'digest': ErrorDetail(string='acb3bca769a78928e95d188c519bae8c4abada60ec87cec2fdce959ba88bc703', code='parse_error')}}]}",`

**To Reproduce**

**Expected behavior**

**Additional context**
podman pull from dockerhub succeeds

**Comment by lubosmj** [comment]
I surfed the internet and came to the conclusion that we should change the requirements just to cope with discrepancies.

The specs say:
> This should generally be application/vnd.docker.container.image.v1+json.

It does not tell us whether it is a MUST (see the section `mediaType for JSON config objects` https://docs.docker.com/registry/spec/manifest-v2-2/). Many sources have a notion about octet-stream - https://wheleph.gitlab.io/posts/2016-07-13-tagging-using-docker-registry-http-api-v2/, https://stackoverflow.com/questions/36489874/docker-pull-failed-manifest-invalid-manifest-invalid-artifactory and no one is complaining about it.

I tried to sync the content with added "application/octet-stream" to the enum in question (https://github.com/pulp/pulp_container/blob/6c2a789deff6b8f1c9a7e9bdd874bad318d17eb9/pulp_container/app/json_schemas.py#L150) and the sync task succeeded. Furthermore, I was able to pull the image with podman:
```
podman pull localhost:24817/library/busybox:1.24.2-musl --tls-verify=false
```
