### ISSUE TITLE
As a user, I can mirror cosign type signatures

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1166]

**Comment by ipanova** [comment]
Cosign signatures are stored in the format of an OCI image manifest. This image has specific rules for tags. The tag is the format of sha256 of the signed image and .sig extension. For example, if image with digest sha256:12345 was signed with cosign, an oci image manifest will be created and tagged as `sha256:12345.sig`

That manifest will contain layer with the simplesigning media_type which will contain the signature payload.
