### ISSUE TITLE
As a user, I can cosign images via Pulp Container Registry

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1168]

**Comment by lubosmj** [comment]
This might not be required right now. It requires further analysis.

**Comment by ipanova** [comment]
I am going to close this for now.
1) There is no direct request for this
2) Compared to podman/skopeo which produces just one file ( the signature), Cosign produces a whole OCI image that contains the signature payload, which later on is being uploaded via the registry API. Cosign does not provide an ability to produce that image and store the output in a dir so later on assets can be upload via Pulp API, like we do here https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/builder.py#L49 ...still a lot of work.)

Now, if we want to create a signing service that will be producing cosign signature, we'd create a signing script which will be containing `cosign sign --key cosign.key pulp-registry/ipanova/cosign-test:latest`. A pulp signing  task will be triggered via pulp API, it will hold exclusive lock on the repo. Task in the subprocess will invoke the cosign command which in return will create an OCI image and try to upload it via Pulp Container Registry v2 API( basically image push). Push process( other tasks like blob put, manifest put)  will try to get an exclusive lock on the same repo and it will fail.
