### ISSUE TITLE
specify a range for include tags to create a container remote

### ISSUE THREAD

**Issue by lfu** [pulp/pulp_container#1171]
**Is your feature request related to a problem? Please describe.**
From user's experience, it would be nice if range is supported for include tags like  "v[15-18].?".
For details, see the original [request](https://community.theforeman.org/t/how-to-specify-a-range-for-include-tags-when-creating-a-new-product-type-docker/31513).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by lubosmj** [comment]
The implementation might not be trivial based on the points I have shared. I am closing this issue because of that.

I still invite you to re-open the issue under the will to contribute the feature to the code base.
