### ISSUE TITLE
Can't configure authentication on token API

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulp_container#1254]
**Version**
2.14.3

**Describe the bug**
Automation Hub relies on being able to configure the default DRF authentication classes in order to be able to provide podman and docker authentication when keycloak is configured. 

**Expected behavior**
The token API on the container registry is hard coded to use basic auth and can't be reconfigured

**Comment by lubosmj** [comment]
https://github.com/pulp/pulp_container/commit/3979fb6ed15d1a809b03b71718341d6ba3e7124b
