### ISSUE TITLE
Repository remove content endpoint doesn't remove content

### ISSUE THREAD

**Issue by sjha4** [pulp/pulp_container#1270]
**Version**
```
  "versions": [
    {
      "component": "core",
      "version": "3.22.2",
      "package": "pulpcore"
    },
    {
      "component": "rpm",
      "version": "3.19.2",
      "package": "pulp-rpm"
    },
    {
      "component": "python",
      "version": "3.8.0",
      "package": "pulp-python"
    },
    {
      "component": "file",
      "version": "1.12.0",
      "package": "pulp-file"
    },
    {
      "component": "deb",
      "version": "2.20.1",
      "package": "pulp_deb"
    },
    {
      "component": "container",
      "version": "2.14.3",
      "package": "pulp-container"
    },
    {
      "component": "certguard",
      "version": "1.5.6",
      "package": "pulp-certguard"
    },
    {
      "component": "ansible",
      "version": "0.16.0",
      "package": "pulp-ansible"
    }
  ]
```
**Describe the bug**
Calling the remove API : `POST /pulp/api/v3/repositories/container/container/85c0f032-a5c0-46f6-a04e-48f33c87ff1f/remove` with params `{"content_units":["/pulp/api/v3/content/container/manifests/e9fc14e7-f62f-47d9-b2fd-43230d354aa3/"]}` doesn't actaully remove the content from the repository. The task is started and returns no new created resources where we'd expect a new version to get created.

For ruby bindings, this is what the flow looks like:

```
16:47:58 rails.1   | 2023-04-21T16:47:58 [D|kat|77a1c0ba] Calling API: RepositoriesContainerApi.remove ...
16:47:58 rails.1   | 2023-04-21T16:47:58 [D|kat|77a1c0ba] HTTP request body param ~BEGIN~
16:47:58 rails.1   |  77a1c0ba | {"content_units":["/pulp/api/v3/content/container/manifests/e9fc14e7-f62f-47d9-b2fd-43230d354aa3/"]}
16:47:58 rails.1   |  77a1c0ba | ~END~
16:47:58 rails.1   |  77a1c0ba | 
16:47:58 rails.1   | 2023-04-21T16:47:58 [D|kat|77a1c0ba] HTTP response body ~BEGIN~
16:47:58 rails.1   |  77a1c0ba | {"task":"/pulp/api/v3/tasks/e9aec6ed-a6ff-4b92-80ea-b836e9780592/"}
16:47:58 rails.1   |  77a1c0ba | ~END~
16:47:58 rails.1   |  77a1c0ba | 

```

This is what the pulp task output looks like:
![Container_remove_content](https://user-images.githubusercontent.com/21146741/233692773-df3a083a-4da0-43cd-98f4-6459d7ccac00.png)

**To Reproduce**
Create a conteiner repo ex: URL: https://quay.io/ , upstream repo: quay/busybox
Sync, this should create repo version 1 and bring down 1 manifest
Call remove API with updated hrefs:
`POST /pulp/api/v3/repositories/container/container/85c0f032-a5c0-46f6-a04e-48f33c87ff1f/remove` with params `{"content_units":["/pulp/api/v3/content/container/manifests/e9fc14e7-f62f-47d9-b2fd-43230d354aa3/"]}`

The task doesn't remove the unit and does not create a new version with updated contents.

**Expected behavior**
The content unit should be deleted and a new version should get created and returned in the pulp task output.

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by lubosmj** [comment]
There might be a chance that the manifest is referenced by a tag that is in the repository.

https://docs.pulpproject.org/pulp_container/workflows/manage-content.html#recursively-remove-content-from-a-repository

Can you share the list of tags and manifests in the repository?

```
http GET /pulp/api/v3/content/container/tags/?repository_version=/blabla/
```

**Comment by ipanova** [comment]
as @lubosmj  pointed out you are removing a manifest that is referenced by a tag so you whether first untag it or directly remove by tag. Please refer to the docs and feel free to re-open the issue if your problem persists.
