### ISSUE TITLE
Make Manifest content type artifactless

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1288]
Currently, `Manifests` have an artifact which is stored in the artifact storage - the `manifest.json` file.

The proposal is move out the `content_artifact.artifact` of a `Manifest` content into a field onto its DB model. `The manifest.json` is designed to be small so storing it in the DB, unlike the blobs ( which are binary data that can be large) should not be a concern.

Reasoning behind:
1. `manifest.json` file contains a lot of information and we  store just some of it on the model in the db. Everytime when we discover the need in the information that we do not have on the model we a) whether need to read this file from disk and parse it b) add the missing information onto the model that as a result brings a migration too.
2. `OCI manifest.json` specs change. At lease for the past year there were 2 spec change which have added new fields or renamed them.

By storing the json file in the DB it will be much cheaper the load it from the DB then from FS.

**Note** Out of scope but question is of the similar nature - `Config blobs` which are also json files could be stored in the DB as well, since this is where `Labels` of a container are defined, however, our model `Blob` covers also regular blobs ( large binary data) so we will whether need to split `ConfigBlob` into its separate model ( meh solution :/) or add a new field on the existing model which deepening on the `media_type` of the blob will whether have it populated or have the blob.content_artifact.artifact ( also meh solution :/)

**Comment by mdellweg** [comment]
Re config blobs: Having the Config blob as a separate content type would keep the number of artifacts per Blob constant (at 1). This is probably the solution with less surprises. At that point I would, for flexibility, have an ArtifactBlob and a DBBlob (both inheriting the generic Blob) so we can onboard future blob types easily.
However _just_ making the (single) Blob type capable of inlining next to artifact storage also has some nice aspects to it. I think we could make that even in a zero downtime manner.

**Comment by lubosmj** [comment]
Two things to consider. We will need to change the sync pipeline because the artifact will no longer be present in the filesystem. We should also handle the reclamation task: Remove: PROTECTED_FROM_RECLAIM = False.

For the blobs thingy, we could open a separate issue to track the progress.

**Comment by lubosmj** [comment]
I opened a new issue to track the blob model's refactorization: https://github.com/pulp/pulp_container/issues/1296

**Comment by lubosmj** [comment]
Do we want to have this data saved into `JSONField` or saved as a string? https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.JSONField

**Comment by ipanova** [comment]
+1 to jsonfield
