### ISSUE TITLE
Establish a new artifactless Blob Config model

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1296]
https://github.com/pulp/pulp_container/issues/1288#issuecomment-1560638504

Ultimately, we will have two models -- one for config blobs, and another for regular blobs. Only the former one will be artifactless since it stores less information.

**Comment by git-hyagi** [comment]
After considering the benefits this change would bring and analyzing and identifying some complexities with it, the team decided to keep the current implementation as is (more details in https://github.com/pulp/pulp_container/pull/1603#issuecomment-2084939231 discussion).
