### ISSUE TITLE
Signing task should ignore cosign produced signatures, attestations and sboms

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1347]
**Version**
all

**Describe the bug**
Atomic signature signing task signs images. Cosign signatures, attestations and sboms are presented as an image too. We should ignore them and not sign. 

**To Reproduce**
Trigger atomic signature pulp signing task ( skopeo signing)

**Expected behavior**
it does not make sense to sign cosign produced signatures, attestations and sboms

**Additional context**
We can filter out tags that end in  `.sig, .att, .sbom`  https://github.com/pulp/pulp_container/blob/main/pulp_container/app/tasks/sign.py#L50

An sbom *can* be signed, but I don't know how much it makes sense to sign it with skopeo?

**Comment by lubosmj** [comment]
> An sbom can be signed, but I don't know how much it makes sense to sign it with skopeo?

Are not SBOMs usually signed by cosign (https://edu.chainguard.dev/open-source/sigstore/cosign/how-to-sign-an-sbom-with-cosign/#sign-the-sbom)? So, the question is about signing them once again with skopeo? If yes, it does not make sense to sign them once again. Could the added value be that we will provide another source of truth?

**Comment by ipanova** [comment]
Yes. that is the question and the solution to it would be to ignore  tags that end in .sig, .att, .sbom.

> Could the added value be that we will provide another source of truth?
I don't know. I think it requires more research whether it makes sense. It is *possible* to sign an sbom with skopeo and anything else that is represented as an image ( so also attestations and signatures) but the question is - does it make any sense.
