### ISSUE TITLE
Concurrent container pushes result in `unsupported: Request was throttled.` and client exiting

### ISSUE THREAD

**Issue by m-bull** [pulp/pulp_container#1396]
**Version**
```
  "versions": [
    {
      "component": "core",
      "version": "3.21.2",
      "package": "pulpcore"
    },
    {
      "component": "container",
      "version": "2.14.2",
      "package": "pulp-container"
    }
  ],
```

**Describe the bug**
When pushing images, clients report:
```
unsupported: Request was throttled.
```

Server logs look like:
```
Sep 14 15:45:38 ark gunicorn[55416]: pulp [892eecd959ac4924b40435dfe2d70503]: django.request:WARNING: Too Many Requests: /v2/namespace/ubuntu-source-tgtd/blobs/uploads/12f66b30-8532-488e-a5cc-8a6e0c0347e2
Sep 14 15:45:38 ark gunicorn[55416]: pulp [892eecd959ac4924b40435dfe2d70503]: 127.0.0.1 - - [14/Sep/2023:15:45:38 +0000] "PUT /v2/namespace/ubuntu-source-tgtd/blobs/uploads/12f66b30-8532-488e-a5cc-8a6e0c0347e2?digest=sha256%3Acd55262f3176fd0dcbd642736f6fdeb4beec539402ac06abfc9dd4d8960d769a HTTP/1.0" 429 82 "-" "docker/20.10.23 go/go1.18.10 git-commit/6051f14 kernel/4.18.0-408.el8.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.23 \(linux\))"
```

Client is not happy about the 429 and quits without backing off.

EDIT: I wonder if this is a reverse-proxy config issue - I can see `127.0.0.1` in the logs. It would make sense to throttle requests if it looked like they all came from `127.0.0.1`!

**To Reproduce**
Push some images into Pulp. These images do have many layers, and are pushed concurrently from a couple of hosts, all NATed behind the same IP address.

Generally we would expect somewhere in the region of a max of 20 concurrent pushes from (what looks like) the same IP.

**Expected behavior**
Either:
  - Requests are throttled at some configurable threshold.
  - Clients gracefully accept the "too many requests" and backoff.

**Comment by ipanova** [comment]
are you using docker for pushing or podman?

**Comment by lubosmj** [comment]
Is this run in a highly concurrent environment? Is there a chance you can upgrade to a newer version of pulp_container? We released 2.15 with a fix to a similar issue: https://github.com/pulp/pulp_container/issues/1212.

**Comment by ipanova** [comment]
What @lubosmj  suggested.
Also FYI docker does not honor 429 at all. It just fails and does not back off.. :)
From your paste I can see that podman did backoff and re-tried as expected just pulp did not managed in that allocated time to finish the upload.

**Comment by m-bull** [comment]
Oh, `pulpcore` upgrade required too, guess this means its time to migrate from `pulp_installer` to `pulp-in-one`...

**Comment by ipanova** [comment]
yes, here are some docs in case they'd come in handy https://docs.pulpproject.org/pulp_oci_images/migration-pulp-installer-to-multi-process/

**Comment by lubosmj** [comment]
@m-bull, any updates on this issue?

**Comment by m-bull** [comment]
We've scheduled the work to move to pulp-oci-images, but not completed yet. I'm happy to close this issue and re-open if we're still encountering issues after the update.
