### ISSUE TITLE
Our OCI support is out of sync with the latest updates to the spec

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1494]
**Version**
1. We do not support - manifest.json with artifactType, subject https://github.com/opencontainers/image-spec/blob/main/manifest.md
2.  Descriptor properties need to be updated - urls, data, artifactType https://github.com/opencontainers/image-spec/blob/main/config.md
3. We need to handle empty descriptor mediatype https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidance-for-an-empty-descriptor
4. We might want to reconsider out media_type validation for config, layers, and instead ignore if unknown https://github.com/opencontainers/image-spec/blob/main/artifacts-guidance.md https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by RCMariko** [comment]
The links are great, however for future reference or just quick info - is there a specific version of the spec we are trying to align with in this issue?

**Comment by ipanova** [comment]
it's latest available here https://github.com/opencontainers/image-spec, currently v1.1

**Comment by lubosmj** [comment]
This issue incorporates disabling the media_type validation to some extent.
