### ISSUE TITLE
As a user I want to distribute via registry flatpak delta manifests 

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1495]
**Is your feature request related to a problem? Please describe.**

There are 2 ways how the client can fetch delta manifest:
1. image  contains label `io.github.containers.DeltaUrl` that points to the location where it can be downloaded `https://cdn.flatpaks.redhat.com/deltas/b3/514cf3ce2747f75f4880f108d7b6d65130593fb2a0b767ed481895b328b653.json`
2. Delta manifests have registry protocol implementation and are distributed via and oci artifact https://github.com/flatpak/flatpak-oci-specs/blob/main/image-deltas.md#locating-the-delta-manifest

We should enable number 2.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by lubosmj** [comment]
(2) This means that we will need to allow a new media type to be parsed.

**Comment by lubosmj** [comment]
Related to disabling the validation in https://github.com/pulp/pulp_container/issues/1494.

**Comment by lubosmj** [comment]
After merging https://github.com/flatpak/flatpak-oci-specs/pull/5/files, we should be fine with closing this issue.

1. We do not validate media types of (config) blobs anymore.
2. Manifests' media types are supposedly used in a standard way.
