### ISSUE TITLE
Replace the pyjwkest dependency

### ISSUE THREAD

**Issue by dralley** [pulp/pulp_container#1514]
**Version**
All

**Describe the bug**
pyjwkest has been unmaintained for 4 years, we need to replace it with a library that is maintained.

**Additional context**
Possibly PyJWT?

**Comment by lubosmj** [comment]
This is related to https://github.com/pulp/pulp_container/issues/1509. After removing the conversion machinery, we will eliminate code paths that uses the `pyjwkest` dependency.

**Comment by lubosmj** [comment]
I am closing this since it appears that it is plausible to package pyjwkest with pinned dependencies that do not exhibit vulnerabilities for older releases. For the new releases, we are removing it completely, as mentioned in the comment above.
