### ISSUE TITLE
Pull through cache question

### ISSUE THREAD

**Issue by anthonyra** [pulp/pulp_container#1544]
**Version**
```json
        {
            "component": "core",
            "domain_compatible": true,
            "module": "pulpcore.app",
            "package": "pulpcore",
            "version": "3.49.0"
        },
        {
            "component": "ansible",
            "domain_compatible": false,
            "module": "pulp_ansible.app",
            "package": "pulp-ansible",
            "version": "0.21.3"
        },
        {
            "component": "container",
            "domain_compatible": false,
            "module": "pulp_container.app",
            "package": "pulp-container",
            "version": "2.18.0"
        },
        {
            "component": "deb",
            "domain_compatible": false,
            "module": "pulp_deb.app",
            "package": "pulp_deb",
            "version": "3.2.0"
        },
        {
            "component": "gem",
            "domain_compatible": true,
            "module": "pulp_gem.app",
            "package": "pulp-gem",
            "version": "0.5.0"
        },
        {
            "component": "maven",
            "domain_compatible": false,
            "module": "pulp_maven.app",
            "package": "pulp-maven",
            "version": "0.8.0"
        },
        {
            "component": "ostree",
            "domain_compatible": true,
            "module": "pulp_ostree.app",
            "package": "pulp-ostree",
            "version": "2.3.0"
        },
        {
            "component": "python",
            "domain_compatible": false,
            "module": "pulp_python.app",
            "package": "pulp-python",
            "version": "3.11.0"
        },
        {
            "component": "rpm",
            "domain_compatible": true,
            "module": "pulp_rpm.app",
            "package": "pulp-rpm",
            "version": "3.25.1"
        },
        {
            "component": "certguard",
            "domain_compatible": true,
            "module": "pulp_certguard.app",
            "package": "pulpcore",
            "version": "3.49.0"
        },
        {
            "component": "file",
            "domain_compatible": true,
            "module": "pulp_file.app",
            "package": "pulpcore",
            "version": "3.49.0"
        }
```

Using the single container image.

**Describe the bug**

When using tokens to pull from pull through cache the following warning occurs

```plaintext
pulp [c4160f6bab16460783713aa7202d52a4]: django.request:WARNING: Unauthorized: /v2/library/hello-world/manifests/latest
```

**To Reproduce**

Setup pulp3 via the `pulp-oci-images` documenation.

**Expected behavior**

I would imagine that the manifest request would be authorized. When using httpie the following is returned
```plaintext
HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, PUT, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 106
Content-Type: application/json
Correlation-ID: 85675fc3f9b14606945b0e21e297c9f4
Cross-Origin-Opener-Policy: same-origin
Date: Mon, 11 Mar 2024 20:25:43 GMT
Docker-Distribution-Api-Version: registry/2.0
Referrer-Policy: same-origin
Server: nginx/1.22.1
WWW-Authenticate: Bearer realm="http://pulp3.lxd:8080/token/",service="pulp3.lxd:8080",scope="repository:library/hello-world:pull"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Registry-Supports-Signatures: 1

{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "detail": {},
            "message": "Authentication credentials were not provided."
        }
    ]
}
```

Which the `WWW-Authenticate` header matches the token being passed in via `docker pull` and when you manually get a token with httpie.

**Additional context**
None

**Comment by lubosmj** [comment]
When you run `docker pull`, the `docker` utility fetches the token from the authorization header and proceeds with the request by getting manifests and blobs.

The same goes when you want to get the token manually. See the examples provided at https://docs.pulpproject.org/pulp_container/authentication.html#token-authentication-label. When using `httpie`, you should pass the returned token via the options `--auth-type=jwt` and `--auth=TOKEN` (https://github.com/teracyhq/httpie-jwt-auth).

Feel free to correct me if I am getting it wrong but I think this is correct behaviour. Can you pull images from Pulp? If not, can you share more details on how you create the pull-through caching distribution and remote? In general, the warnings you have shared should not be something you need to worry about.

**Comment by anthonyra** [comment]
It appears that I'm able to pull the image just that I get the above warning when I do. I then try to do it manually with `httpie` with the jwt plugin using the provided `WWW-authenticate` header information and it still returns unauthorized. If this is expected behavior that's all I'm really looking for. If it's not expected behavior I thought I'd raise the concern.

**Comment by anthonyra** [comment]
Also, I can't seem to view `/v2/_catolog` with tokens enabled. Using `httpie` and following the process of getting the token with the `WWW-authenticate` information.


> http pulp3.lxd:8080/v2/_catalog
```bash
HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 106
Content-Type: application/json
Correlation-ID: 4d58cb1a53fb43d2af6161eddcf76308
Cross-Origin-Opener-Policy: same-origin
Date: Tue, 12 Mar 2024 11:41:41 GMT
Docker-Distribution-Api-Version: registry/2.0
Referrer-Policy: same-origin
Server: nginx/1.22.1
Vary: Accept
WWW-Authenticate: Bearer realm="http://pulp3.lxd:8080/token/",service="pulp3.lxd:8080",scope="registry:catalog:*"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Registry-Supports-Signatures: 1

{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "detail": {},
            "message": "Authentication credentials were not provided."
        }
    ]
}
```
> token=$(http "pulp3.lxd:8080/token/?service=pulp3.lxd:8080&scope=registry:catalog:*" | jq .token)
```plaintext
"eyJhbGciOiJFUzI1NiIsImtpZCI6IkdFM0c6RU1MRzpNTTJUOktNSlM6SEEzVDpHTVJVOkc0Wkc6TU5KWjpNRlNXOkNaSlg6TU00VDpTT0JWIiwidHlwIjoiSldUIn0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZWdpc3RyeSIsIm5hbWUiOiJjYXRhbG9nIiwiYWN0aW9ucyI6W119XSwiYXVkIjoicHVscDMubHhkOjgwODAiLCJleHAiOjE3MTAyNDQxMTEsImlhdCI6MTcxMDI0MzgxMSwiaXNzIjoiaHR0cDovL3B1bHAzLmx4ZDo4MDgwL3Rva2VuLyIsImp0aSI6IjE2ODZjZjU3LTBhYWQtNGM5OS05NjQ3LTI0OTJlZjExMzBjOSIsIm5iZiI6MTcxMDI0MzgxMSwic3ViIjoiIn0.-BkiS09SIL5NAsFz6YgXFORJMbmWwI0cLBQMJpurIclrnyNQg4qwcUk-Z_wEvgkTa9ETXveUr2dsZcbCr8QolA"
```
> http --auth-type=jwt --auth=$token pulp3.lxd:8080/v2/_catalog
```bash
HTTP/1.1 401 Unauthorized
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 150
Content-Type: application/json
Correlation-ID: 375c7a658c8e49818fdc724edb784b6f
Cross-Origin-Opener-Policy: same-origin
Date: Tue, 12 Mar 2024 11:44:46 GMT
Docker-Distribution-Api-Version: registry/2.0
Referrer-Policy: same-origin
Server: nginx/1.22.1
Vary: Accept
Www-Authenticate: Bearer realm="http://pulp3.lxd:8080/token/",service="pulp3.lxd:8080",scope="registry:catalog:*",error="invalid_token"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Registry-Supports-Signatures: 1

{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "detail": {},
            "message": "Access to the requested resource is not authorized. The provided Bearer token is invalid."
        }
    ]
}
```

**Comment by lubosmj** [comment]
The catalog endpoint is accessible for admins by default (admin:password). Are you using anonymous tokens to access the endpoint?

**Comment by anthonyra** [comment]
I am, but with the pull through cache feature (I couldn't find out how to do it with pulp CLI) you have to use `httpie` so I removed all `rest_framework` (I understand security but it's all locally being ran) permissions. I'm able to access everything but what's under the `/v2/` umbrella because I think that's now using the token.

**Comment by ipanova** [comment]
@anthonyra can you share the token you're getting while trying to access the repo, in yuor case `library/hello-world`

**Comment by ipanova** [comment]
getting a warning of 401 is fine, because the client first reaches out to the registry without any auth, it gets warning, 401 and info in the auth header how to get a token. gets token and then reaches out the registry again with a token and should get 200. and so if on the last step you get still 401 there are few scenarios:
1. there is a bug in pulp container
2.  your user does not have according permissions to reach repo contents
3. maybe something was not setup in a correct way so please share all the steps you have performed from the very beginning.

**Comment by anthonyra** [comment]
@ipanova
### install pulp
#### create directories
```bash
sudo mkdir -p settings pulp_storage/tmp
```
#### tokens
```bash
sudo openssl ecparam -genkey -name prime256v1 -noout -out ~/pulp_storage/tmp/private_key.pem
```

```bash
sudo chmod 600 ~/pulp_storage/tmp/private_key.pem
```

```bash
sudo openssl ec -in ~/pulp_storage/tmp/private_key.pem -pubout -out ~/pulp_storage/tmp/public_key.pem
```

```bash
sudo chmod 644 ~/pulp_storage/tmp/public_key.pem
```
#### settings
```bash
sudo nano settings/settings.py
```
```bash
CONTENT_ORIGIN                             = "http://localhost:8080"

TOKEN_SERVER                               = "http://localhost:8080/token/"
TOKEN_SIGNATURE_ALGORITHM                  = "ES256"
PUBLIC_KEY_PATH                            = "/var/lib/pulp/tmp/public_key.pem"
PRIVATE_KEY_PATH                           = "/var/lib/pulp/tmp/private_key.pem"

### set to allow access to `/pulp/api/v3/` with tokens enabled
REST_FRAMEWORK__DEFAULT_PERMISSION_CLASSES = [
   "rest_framework.permissions.AllowAny",
]
```
#### docker run prep
```bash
sudo chown -R 700:700 settings pulp_storage
```
#### docker run
```bash
sudo docker run --detach \
	--publish 8080:80 \
	--name pulp \
	--volume "$HOME/settings":/etc/pulp \
	--volume "$HOME/pulp_storage":/var/lib/pulp \
	--volume "$HOME/pgsql":/var/lib/pgsql \
	--volume "$HOME/containers":/var/lib/containers \
	--device /dev/fuse \
	pulp/pulp
```
#### setup docker.io pull through
```
HREF=$(http pulp3.lxd:8080/pulp/api/v3/remotes/container/pull-through/ name=docker.io url=https://index.docker.io | jq -r ".pulp_href")
```

```bash
http pulp3.lxd:8080/pulp/api/v3/distributions/container/pull-through/ remote=${HREF} name=docker.io base_path=docker.io
```

**Comment by lubosmj** [comment]
Thanks for the information. I do not see any problems with your setup.

> If this is expected behavior that's all I'm really looking for. If it's not expected behavior I thought I'd raise the concern.

I would call it the the expected behaviour. The problem would be if you could not pull an image from the pull-through distribution. 

> http pulp3.lxd:8080/pulp/api/v3/distributions/container/pull-through/ remote=${HREF} name=docker.io base_path=docker.io

We have not added support for creating pull-through distributions to the CLI yet. Once you create the distribution, you want to run `docker pull pulp3blabla/docker.io/library/busybox` and Pulp should download and stream the `latest` available image without any errors.

When using `httpie` for debugging purposes, make sure you request your tokens with a correct user. The `_catalog` endpoint is accessible for all **AUTHENTICATED** users, but only administrators can see all (private) repositories. It does not matter whether you have disabled the `rest_framework` authentication machinery or not. We are dealing with different authentication concepts here -- token authentication & rest_framework. These two do not relate.

In your example, I am not seeing `"sub": "user"` in your token (https://jwt.io/). Thus, you are using an anonymous token to access the endpoint:

![image](https://github.com/pulp/pulp_container/assets/8740962/a831beab-af82-40cc-b400-2062fcaf6a27)

------------------------------------------------------------------

When I run this workflow manually on a fresh install, I get this:
```
http http://localhost:8080/token/?service="localhost:8080"'&'scope="registry:catalog:*" -a admin:password
```
```
{
    "access_token": "eyJhbGciOiJFUzI1NiIsImtpZCI6IkhBM0c6R05SVzpHTlNUOkNOQlM6TVlZVDpHTVJVOk1FM0Q6S1pCWjpIQVlEOkFNQlc6R0ZTRzpNWVJVIiwidHlwIjoiSldUIn0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZWdpc3RyeSIsIm5hbWUiOiJjYXRhbG9nIiwiYWN0aW9ucyI6WyIqIl19XSwiYXVkIjoibG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTAyNzI3OTksImlhdCI6MTcxMDI3MjQ5OSwiaXNzIjoiaHR0cDovL2xtamFjaGt5LXRoaW5rcGFkdDE0Z2VuNC5icnEuY3NiOjgwODAvdG9rZW4vIiwianRpIjoiYWM0MjM5N2UtOTFlNi00YzlmLWIwNDAtOTVkOGYxZjQxMzlhIiwibmJmIjoxNzEwMjcyNDk5LCJzdWIiOiJhZG1pbiJ9.SZwP7DBlDBuMLgvrjfY7xd_ytbQl2svsuGX-H6NkEcbkYHXmJDTlYKKxfO3drpbMyuQ7oWK3eTJZ3a896c8XXg",
    "expires_in": 300,
    "issued_at": "2024-03-12T19:41:39.845928Z",
    "token": "eyJhbGciOiJFUzI1NiIsImtpZCI6IkhBM0c6R05SVzpHTlNUOkNOQlM6TVlZVDpHTVJVOk1FM0Q6S1pCWjpIQVlEOkFNQlc6R0ZTRzpNWVJVIiwidHlwIjoiSldUIn0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZWdpc3RyeSIsIm5hbWUiOiJjYXRhbG9nIiwiYWN0aW9ucyI6WyIqIl19XSwiYXVkIjoibG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTAyNzI3OTksImlhdCI6MTcxMDI3MjQ5OSwiaXNzIjoiaHR0cDovL2xtamFjaGt5LXRoaW5rcGFkdDE0Z2VuNC5icnEuY3NiOjgwODAvdG9rZW4vIiwianRpIjoiYWM0MjM5N2UtOTFlNi00YzlmLWIwNDAtOTVkOGYxZjQxMzlhIiwibmJmIjoxNzEwMjcyNDk5LCJzdWIiOiJhZG1pbiJ9.SZwP7DBlDBuMLgvrjfY7xd_ytbQl2svsuGX-H6NkEcbkYHXmJDTlYKKxfO3drpbMyuQ7oWK3eTJZ3a896c8XXg"
}
```

```
http http://localhost:8080/v2/_catalog --auth-type=jwt --auth=eyJhbGciOiJFUzI1NiIsImtpZCI6IkhBM0c6R05SVzpHTlNUOkNOQlM6TVlZVDpHTVJVOk1FM0Q6S1pCWjpIQVlEOkFNQlc6R0ZTRzpNWVJVIiwidHlwIjoiSldUIn0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZWdpc3RyeSIsIm5hbWUiOiJjYXRhbG9nIiwiYWN0aW9ucyI6WyIqIl19XSwiYXVkIjoibG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTAyNzI3OTksImlhdCI6MTcxMDI3MjQ5OSwiaXNzIjoiaHR0cDovL2xtamFjaGt5LXRoaW5rcGFkdDE0Z2VuNC5icnEuY3NiOjgwODAvdG9rZW4vIiwianRpIjoiYWM0MjM5N2UtOTFlNi00YzlmLWIwNDAtOTVkOGYxZjQxMzlhIiwibmJmIjoxNzEwMjcyNDk5LCJzdWIiOiJhZG1pbiJ9.SZwP7DBlDBuMLgvrjfY7xd_ytbQl2svsuGX-H6NkEcbkYHXmJDTlYKKxfO3drpbMyuQ7oWK3eTJZ3a896c8XXg
```
```
{
    "repositories": []
}

```
In my case, I am having `"sub": "admin"`:

![image](https://github.com/pulp/pulp_container/assets/8740962/799fb02a-92e4-4e7e-ae82-ce3a86364b78)

**With an anonymous token, you cannot access this endpoint.**

**Comment by anthonyra** [comment]
Ahh so it appears I need to include the `admin:password` with the token requests when accessing `/v2/_catalog` which is perfectly fine just didn't know I had to include it no matter the `rest_framework` permissions. To clarify, when pulling an image via `docker pull` with an anonymous token should I be seeing that `unauthorized` warning with the manifest? Sounds like it's suppose to but just verifying

**Comment by lubosmj** [comment]
When accessing this endpoint, yes, you should use BasicAuth to tell Pulp's token server that you are an authenticated and authorized user.

`docker pull` runs this procedure in background, as @ipanova highlighted in https://github.com/pulp/pulp_container/issues/1544#issuecomment-1991920936:
1. requests manifest
2. oooh, it requires token, let me query the token server
3. cool, now I am using the retrieved token to request the manifest
4. nice, I can now fetch blobs and finish.

Docker does not care about the catalog endpoint, it goes directly for the manifest and ignores the _catalog endpoint.
