### ISSUE TITLE
Test how much time takes the handle-image django-admin command with OSP content

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#1573]
Test with OSP containers how much time take the handle-image django-admin command
https://catalog.redhat.com/software/containers/search?gs&q=rhosp-rhel8

Steps to setup the testing environment:

1. create repos and remotes
2.  sync with on-demand policy
3. run the django-admin command

**Comment by ipanova** [comment]
I've synced down all RHOSP 16 containers that consisted of:
* 128 repos
* 33k manifests
* 24k image mnaifests

```bash
$ time pulpcore-manager container-handle-image-data
Successfully handled 16115 manifests.

real	2m4.823s
user	1m23.140s
sys	0m5.779s
```

re-run:
```bash
$ time pulpcore-manager container-handle-image-data
Successfully handled 16115 manifests.

real	1m46.769s
user	1m13.260s
sys	0m4.826s

**Comment by lubosmj** [comment]
That is quite fast. 👁️ Does this scenario trigger the updating of manifest objects in the database (e.g., some of the containers are bootable)?

**Comment by ipanova** [comment]
Not bootable and not flapack but the images have labels.

**Comment by ianballou** [comment]
That's really fast, thanks @ipanova ! Assuming the timing is linear, even if users have 30x that content, it's still pretty quick. I think, with that timing in mind, it's safe to make this an automatic post-upgrade step in foreman-maintain.

**Comment by ianballou** [comment]
Also nice to see an improvement was found about the re-run. Sounds like after that issue is dealt with, the re-run really can be a no-op.

**Comment by ianballou** [comment]
cc @sjha4 since you're working on the Pulpcore / pulp-container upgrade as we speak :)

**Comment by ianballou** [comment]
If possible it would be nice to have updated timing information for the other pre-migrations that will need to run, like artifactless manifest.

Is it still planned that `container-handle-image-data` will hold all of the recently planned pre-migrations?

**Comment by ipanova** [comment]
@ianballou  @lubosmj  I think that's still the plan. I don't think the numbers will change much though because in addition to what it is being done here we will move already loaded and parsed data into a new filed in the db.

**Comment by ipanova** [comment]
Here are the results with NFS rotating disk :

```
$ time django-admin container-handle-image-data 
Successfully updated 16132 manifests.

real	6m51.072s vs 2m4.823s
user	3m46.112s
sys	0m13.089s
```
And re-run:
```
$ time django-admin container-handle-image-data 
Successfully updated 0 manifests.

real	2m34.519s vs 0m33.644s
user	1m25.915s
sys	0m5.208s
```

**Comment by ipanova** [comment]
With this PR https://github.com/pulp/pulp_container/pull/1530 it takes 6m on local filesystem and 1.30m re-run.

**Comment by ianballou** [comment]
For me on Pulp Container 2.20 with 120 repositories and 26295 manifests:

```
$ time sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py'  /usr/bin/pulpcore-manager container-handle-image-data
Successfully updated 26295 manifests.
Successfully flushed the cache.

real	7m16.391s
user	4m4.297s
sys	0m19.245s
```

**Comment by ianballou** [comment]
Here's another data point:

Spinning disk

pulp-container 2.20.0

126 repositories
31642 manifests

real    11m5.171s
user    8m5.981s
sys     0m29.593s
