### ISSUE TITLE
Question: How do I view registry content in the browser?

### ISSUE THREAD

**Issue by PotentialIngenuity** [pulp/pulp_container#1661]
When I navigate to my registry in the browser I get `403: Access not authenticated` but the browser does not prompt me for credentials. I am unfamiliar with contentguards or how to configure them. I can see the default one is attached to my registry distribution.

https://registry.company.com/pulp/content/<registry>/<container_names>

**Comment by lubosmj** [comment]
Possible duplicate of https://github.com/pulp/pulp_container/issues/1578.

**Comment by PotentialIngenuity** [comment]
Yes this question is a duplicate. I was able to get the information I was looking for.
