### ISSUE TITLE
pulp_container 2.20.1 Ruby bindings have many method name changes compared to 2.20.0

### ISSUE THREAD

**Issue by ianballou** [pulp/pulp_container#1722]
Seemingly the same or similar issue from https://github.com/pulp/pulpcore/issues/5592 has caused Ruby methods like `list` to turn into `repositories_container_container_list` and so on.

Take a look at the diff here: https://my.diffend.io/gems/pulp_container_client/2.20.0/2.20.1/page/2

pulp_container_client 2.20.0 works just fine.

**Comment by lubosmj** [comment]
Might be fixed by a next release. Please, verify.

**Comment by ianballou** [comment]
2.20.2 is working well for us!

**Comment by lubosmj** [comment]
Amazing! Closing!
