### ISSUE TITLE
Do not log gpg errors for signature sync: gpg returned a non-zero error code: 2

### ISSUE THREAD

**Issue by goosemania** [pulp/pulp_container#519]
When syncing signatures, in order to decode a non-encrypted signed doc, we use `gpg.decrypt`.
There is no verification of the signature, no keys are involved.
GPG would log a `gpg returned a non-zero error code: 2` for every `gpg.decrypt` call (once for every signature, e.g. 156 for a small repo).

This just spams user logs and brings confusion and concern when it should be ignored.

Unfortunately, in python-gnupg code, the it is hard-coded to write such messages to stderr.
Maybe the logger can be configured to ignore those. But it would be good to ignore only those calls and not all the gpg errors which might happen somewhere else in Pulp code base.

**Comment by lubosmj** [comment]
Doing the following disables the logging for the `gnupg` module:

```python
import logging

gnupg_logger = logging.getLogger("gnupg")
gnupg_logger.setLevel(logging.CRITICAL+1)
```

We may do this at the top of the `pulp_container/app/utils.py` file if there is no way to elegantly retrieve the public key beforehand. We may do this at the top of the pulp_container/app/utils.py file if there is no way to elegantly retrieve the public key beforehand. Is there any easy way to obtain the public key @goosemania?

**Comment by goosemania** [comment]
Signature sync should work with or without a key, because we are not verifying it and we are not using any key, just decoding and reading the json payload.
It would be preferable to find a way to ignore logs only for those specific calls and not for the entire gnupg module, because in other parts of the code it might fail for a good reason and we do not want to silently miss those.

**Comment by lubosmj** [comment]
Weird, I just did `crypt_obj = gpg.decrypt(signature_raw, extra_args=["--skip-verify"])` (gpg errors were finally gone) and started to receive the following errors when syncing signatures from the redhat's sigstore:
```
Started background task /pulp/api/v3/tasks/1bc94bb8-c5a7-4f98-a0a3-87cab5dce025/
........................................................................................................................................................................................................Error: Task /pulp/api/v3/tasks/1bc94bb8-c5a7-4f98-a0a3-87cab5dce025/ failed: 'null value in column "key_id" of relation "container_manifestsignature" violates not-null constraint
DETAIL:  Failing row contains (2f5ca68c-5144-4c2e-befe-7c169674e19e, sha256:e7fb65691b8ecd0f7f32e7c779dd05f0da65b6117c6a9d5302a655f36..., sha256:0513955964953dac6e9746aa40cd212fab52745d674c3e6933c70b0fa..., atomic, null, null, Red Hat RCM Pub 0.78.0-final , owGbwMvMwMEoOU9/4l9n2UDGtYw+SWLxRQW5xZnpukWphbpBni7O8Xl6SZl5SbsV..., cfd95360-ae20-4298-bfdd-282ea0006206).
'
```

**Comment by goosemania** [comment]
For the context, I believe that key_id was set as a required field to enable users to search by the key. E.g. the key was compromised and they want to delete all signatures which use that key, or users want to see which signature come from other key providers than their company one, etc.
Maybe it can just be the best effort approach, and key_id would be set only for the verified signatures. At the same time, we are trying to avoid verification within pulp...
Is it possible to get key_id from the signature in some other way? It's not encrypted data, so I would expect it to be available one way or the other.

**Comment by mdellweg** [comment]
When i did the search once, i didn't find a native python lib, but there is: https://datatracker.ietf.org/doc/html/rfc4880

**Comment by lubosmj** [comment]
I am probably going to extract the missing fields from (not the cleanest approach, but it works):
```python
subprocess.check_output(["gpg", "--list-packets"], input=signature_raw).decode()
```
