### ISSUE TITLE
Accept token under the name access_token for compatibility with oauth2

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#619]
**Version**
Please provide the versions of the pulpcore and pulp_container packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
https://docs.docker.com/registry/spec/auth/token/#requesting-a-token

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by fao89** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2026151
