### ISSUE TITLE
Add docs that facilitate manual steps from permissions to roles

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#641]
Pulp-container deployments that used to have custom permissions added outside of default groups that are created during podman push need manual documented steps how perform the switch from custom permisions to roles.

Pulp-container deployments that used default groups don't need to take any manul steps, there is a migration that transforms those grouped permissions into roles.

**Comment by lubosmj** [comment]
@ipanova, do you mean to address this issue in pulpcore at the higher level and then proceed with writing more detailed documentation for pulp_container?

**Comment by ipanova** [comment]
I meant to highlight that our plugin is missing genral rbac docs after the  switch to roles, so i've pointed to some example in file and rpm plugins.
