### ISSUE TITLE
Remove pre-Roles RBAC code with pulpcore 3.20 release

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#678]
https://github.com/pulp/pulp_container/pull/675

**Comment by mdellweg** [comment]
What is the right order of execution now? Can we make pulp_container independent from guardian before we release 3.20? Or does this force us to do a lockstep release again?

**Comment by ipanova** [comment]
@mdellweg I think we can proceed with this changes whenever we will declare pulp_container compatibility with pulpcore 3.20.
Whether this will be before 3.20 release or right after it is up to us.
I would not make a release compatible with 3.19 and 3.20.
