### ISSUE TITLE
Namespace validation is not working

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#688]
**Version**
Please provide the versions of the pulpcore and pulp_container packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
```
$ http https://pulp3-source-fedora34.fluffy.example.com/pulp/api/v3/distributions/container/container/ name=itest2 base_path=sunday/morning3 namespace=other
HTTP/1.1 202 Accepted
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 67
Content-Type: application/json
Correlation-ID: d1e5f84931774f37aa4fa75bf6629689
Date: Mon, 04 Apr 2022 13:48:05 GMT
Referrer-Policy: same-origin
Server: nginx/1.20.1
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "task": "/pulp/api/v3/tasks/524e879f-7a3d-4e5e-8d8f-8de26884bb0f/"
}


(pulp) [vagrant@pulp3-source-fedora34 pulp-cli]$ http https://pulp3-source-fedora34.fluffy.example.com/pulp/api/v3/tasks/524e879f-7a3d-4e5e-8d8f-8de26884bb0f/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, PATCH, DELETE, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 644
Content-Type: application/json
Correlation-ID: b682e6af81ee4bfb985e7cf56b1d5b8e
Date: Mon, 04 Apr 2022 13:48:17 GMT
Referrer-Policy: same-origin
Server: nginx/1.20.1
Strict-Transport-Security: max-age=15768000
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "child_tasks": [],
    "created_resources": [
        "/pulp/api/v3/distributions/container/container/84a571f7-8d0c-4006-9746-d75889758e38/"
    ],
    "error": null,
    "finished_at": "2022-04-04T13:48:05.734049Z",
    "logging_cid": "d1e5f84931774f37aa4fa75bf6629689",
    "name": "pulpcore.app.tasks.base.general_create",
    "parent_task": null,
    "progress_reports": [],
    "pulp_created": "2022-04-04T13:48:05.581493Z",
    "pulp_href": "/pulp/api/v3/tasks/524e879f-7a3d-4e5e-8d8f-8de26884bb0f/",
    "reserved_resources_record": [
        "/api/v3/distributions/"
    ],
    "started_at": "2022-04-04T13:48:05.641339Z",
    "state": "completed",
    "task_group": null,
    "worker": "/pulp/api/v3/workers/f2738843-6e6b-4c02-b3fd-4ed58d7bff1f/"
}


(pulp) [vagrant@pulp3-source-fedora34 pulp-cli]$ http https://pulp3-source-fedora34.fluffy.example.com/pulp/api/v3/distributions/container/container/84a571f7-8d0c-4006-9746-d75889758e38/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 558
Content-Type: application/json
Correlation-ID: 7a78a38fd3e542a7a4d2e4f4523f2e23
Date: Mon, 04 Apr 2022 13:48:37 GMT
Referrer-Policy: same-origin
Server: nginx/1.20.1
Strict-Transport-Security: max-age=15768000
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "base_path": "sunday/morning3",
    "content_guard": "/pulp/api/v3/contentguards/core/content_redirect/74c06de4-e8f3-4b12-a710-a69ba284438a/",
    "description": null,
    "name": "itest2",
    "namespace": "/pulp/api/v3/pulp_container/namespaces/412565d8-a0bd-40cb-9c4c-8d3aacf1978b/",
    "private": false,
    "pulp_created": "2022-04-04T13:48:05.691077Z",
    "pulp_href": "/pulp/api/v3/distributions/container/container/84a571f7-8d0c-4006-9746-d75889758e38/",
    "pulp_labels": {},
    "registry_path": "pulp3-source-fedora34.fluffy.example.com/sunday/morning3",
    "repository": null,
    "repository_version": null
}


(pulp) [vagrant@pulp3-source-fedora34 pulp-cli]$ http https://pulp3-source-fedora34.fluffy.example.com/pulp/api/v3/pulp_container/namespaces/412565d8-a0bd-40cb-9c4c-8d3aacf1978b/
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, DELETE, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 153
Content-Type: application/json
Correlation-ID: 5ad263a6a948493cb7411969e9a732ad
Date: Mon, 04 Apr 2022 13:48:46 GMT
Referrer-Policy: same-origin
Server: nginx/1.20.1
Strict-Transport-Security: max-age=15768000
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "name": "sunday",
    "pulp_created": "2022-04-04T13:48:05.558363Z",
    "pulp_href": "/pulp/api/v3/pulp_container/namespaces/412565d8-a0bd-40cb-9c4c-8d3aacf1978b/"
}

```

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by mdellweg** [comment]
The namespace is not even part of the POST serializer (`pulp debug openapi schema | jq '.components.schemas."container.ContainerDistribution"'`). And that is for a reason. There is really no choice the user can have. The namespace is uniquely identified by the first part of the `base_path`. And we handle this transparently for the user.

**Comment by ipanova** [comment]
@mdellweg if you look closely at the code you will see that it has its own discrepancies https://github.com/pulp/pulp_container/blob/main/pulp_container/app/serializers.py#L302 , which we need to fix one way or the other.
Now, I don't remember what path we've taken - whether to fully manage namespace on behalf of the user, by calling into https://github.com/pulp/pulp_container/blob/main/pulp_container/app/serializers.py#L346
Or let the user specify the name space, and here further perform certain validation https://github.com/pulp/pulp_container/blob/main/pulp_container/app/serializers.py#L340

If you read my comments here, you will see that it also points out that this line is never called, because the field is set to read_only=True https://github.com/pulp/pulp_container/pull/680#issuecomment-1087807668
Having that said, we whether enable user to specify the namespace but perform the validation or we fully manage it but then remove the validation.

The reason this issue was opened is because of the presence of the namespace validation in the code, which implies that it validates data provided by the user.

**Comment by mdellweg** [comment]
I'd really vote for managing on behalf of the user. There is literally no choice for the user. It sounds like a tedious exercise to ask them. The thing we should really check is what happens when we change the `base_path` of the distribution (do we even allow that?). At that point the validation might trigger and disallow to move a distribution from one namespace to another.

**Comment by ipanova** [comment]
> I'd really vote for managing on behalf of the user. There is literally no choice for the user. It sounds like a tedious exercise to ask them.

Yeah, i don't mind which way we go. In that case i am removing the validation which is useless and confusing

> The thing we should really check is what happens when we change the `base_path` of the distribution (do we even allow >that?). At that point the validation might trigger and disallow to move a distribution from one namespace to another.

**Comment by mdellweg** [comment]
As long as the namespace permission is checked if the new namespace existed already that's fine for me.

**Comment by ipanova** [comment]
> 
Permissions are a separate saga, those need to be fixed too. I am doing that in a separate PR.
ATM, we're not checking whether user has permission to create new namespace or have read perm on existing one
