### ISSUE TITLE
Can't install pulp-ansible and pulp-container together

### ISSUE THREAD

**Issue by fao89** [pulp/pulp_container#772]
```
File "/usr/local/lib/python3.9/site-packages/pulpcore/app/settings.py", line 87, in <module>
      plugin_app_config = entry_point.load()
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in load
      self.require(*args, **kwargs)
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in require
      items = working_set.resolve(reqs, env, installer, extras=self.extras)
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
      raise VersionConflict(dist, req).with_context(dependent_req)
  pkg_resources.ContextualVersionConflict: (jsonschema 4.4.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('jsonschema>=4.5.1'), {'ansible-lint'})
  ```
  https://github.com/pulp/pulp-operator/runs/6397340639?check_suite_focus=true

**Comment by lubosmj** [comment]
Right now, we have this in pulp_container: https://github.com/pulp/pulp_container/blob/459cfab4605fa060f1e146a40e61e85141877601/requirements.txt#L6

In pulp_ansible, we have:
https://github.com/pulp/pulp_ansible/blob/a5f8a34db3e66e8c5f9008a3dcc4bd79ff754bc6/requirements.txt#L5

It seems like the "operator" was not able to resolve dependencies and it all ended up in an inconsistent state.

The question is whether we should move the dependency to pulpcore to prevent the installation failures, @ipanova, @mdellweg.

**Comment by fao89** [comment]
Actually, pulp-ansible depends on [galaxy-importer](https://github.com/pulp/pulp_ansible/blob/a5f8a34db3e66e8c5f9008a3dcc4bd79ff754bc6/requirements.txt#L3) and it depends on [ansible-lint](https://github.com/ansible/galaxy-importer/blob/master/setup.cfg#L20) and ansible-lint is pinning jsonschema:
https://github.com/ansible/ansible-lint/blob/main/requirements.txt#L35

**Comment by lubosmj** [comment]
I have opened a PR. I am not sure what should be the changelog message.

`Resolved jsonschema versioning while multiple plugins are being installed by the ansible installer`?

**Comment by ipanova** [comment]
With upper bound limits pulp_ansible will anyway need to specify one otherwise it would not be able to release https://github.com/pulp/pulp_ansible/blob/main/requirements.txt
@lubosmj So removing the upper bound for pulp_container is not a solution. We can solve this by ~=4.4 but then we'd need to know whether jsonschema follows semantic versioning or not.

I see that ansible-lint really pins down all the deps :/ https://github.com/ansible/ansible-lint/blob/main/requirements.txt

**Comment by mdellweg** [comment]
I agree that we should relax the requirement on the pulp_container (>4.4,<4.6) side. But i am not happy about the pinning down in the dependence of the dependence of pulp_ansible.

**Comment by webknjaz** [comment]
> and ansible-lint is pinning jsonschema:\nhttps://github.com/ansible/ansible-lint/blob/main/requirements.txt#L35

_(speaking with both my PyPI and Red Hat on)_

You've got a false impression. It's a dev/test constraints file. It is no way exposed in the package metadata. What you're looking for is `setup.cfg`. Which reveals the actual dependency declaration being `jsonschema >= 4.5.1`. This is what you also see in the log posted at the top of this thread.

v4.4.0 version request is coming from elsewhere, not from `ansible-lint`. The source should probably be visible in the full log.

**Comment by ipanova** [comment]
> > > and ansible-lint is pinning jsonschema:\nhttps://github.com/ansible/ansible-lint/blob/main/requirements.txt#L35
> > 
> > 
> > _(speaking with both my PyPI and Red Hats on)_
> > You've got a false impression. It's a dev/test constraints file. It is no way exposed in the package metadata. What you're looking for is `setup.cfg`. Which reveals the actual dependency declaration being `jsonschema >= 4.5.1`. This is what you also see in the log posted at the top of this thread.
> > v4.4.0 version request is coming from elsewhere, not from `ansible-lint`. The source should probably be visible in the full log.

Thanks for clarification, this is where we should look at instead https://github.com/ansible/ansible-lint/blob/main/setup.cfg#L69
> 
> `jsonschema ~= 4.4.0` is coming from https://github.com/pulp/pulp_container/blob/main/requirements.txt#L6 (as a direct request) which caused a conflict with `ansible-lint`'s dependency having a lower bound `jsonschema >= 4.5.1`.

yeah this one we're going to relax to ~=4.4
